# Generated by Django 5.1.1 on 2024-09-22 06:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0002_alter_cart_quantity_alter_cart_total_cost"),
    ]

    operations = [
        migrations.AlterField(
            model_name="favorite",
            name="fav_rating",
            field=models.IntegerField(default=1),
        ),
    ]
