# Generated by Django 5.1.1 on 2024-09-23 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0003_alter_favorite_fav_rating"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="download_link",
            field=models.URLField(blank=True, null=True),
        ),
    ]