# Generated by Django 5.1.1 on 2024-10-12 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_folk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='subcategory',
            new_name='category',
        ),
    ]
