# Generated by Django 5.1.1 on 2024-09-23 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0005_orderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="book",
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to="store.book"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="download_link",
            field=models.URLField(
                default="https://default-link.com/download", max_length=400
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(),
        ),
    ]
