# Generated by Django 5.1.1 on 2024-09-25 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_order_book_alter_book_download_link_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_art',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
