# Generated by Django 5.1 on 2024-10-05 05:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0008_alter_user_first_name_alter_user_last_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="cover_art",
            field=models.URLField(blank=True, null=True),
        ),
    ]
