# Generated by Django 5.1.1 on 2024-10-01 11:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_order_accessory_order_book_wrap_order_booklet_folder_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Exlibris',
            new_name='Bookmark',
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='exlibris',
            new_name='bookmark',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='exlibris',
            new_name='bookmark',
        ),
    ]
