# Generated by Django 5.1 on 2024-10-05 07:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0010_favorite_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="cartitem",
            name="order",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                to="store.order",
            ),
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]
