# Generated by Django 5.1 on 2024-10-05 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0012_remove_cartitem_order_orderitem"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="email_sent_date",
        ),
        migrations.AddField(
            model_name="cartitem",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cart_items",
                to="store.order",
            ),
        ),
        migrations.AddField(
            model_name="cartitem",
            name="ordered",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="OrderItem",
        ),
    ]