# Generated by Django 5.1 on 2024-10-05 14:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0014_alter_cartitem_quantity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="download_link",
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
