# Generated by Django 5.1 on 2024-10-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0015_alter_book_download_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="subcategory",
            name="name",
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=20),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=30),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]