# Generated by Django 5.1.1 on 2024-10-06 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_cart_quantity_alter_cart_total_cost'),
        ('store', '0017_alter_cartitem_cart'),
    ]

    operations = [
    ]
